# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               notebook
tagline:             'This is my personal notebook ^_^'
description:         ''
url:                 
baseurl:             xzenggit.github.io/cn/
paginate:            5

# About/contact
author:
  name:              Xiangming Zeng
  url:               ''
  email:             ''

# Custom vars
version:             1.0.0
